import ScaleWordTheorems.Basic
import ScaleWordTheorems.MOS
import ScaleWordTheorems.Permutation
import ScaleWordTheorems.MV3
import ScaleWordTheorems.PairIdentificationAndDeletion
import ScaleWordTheorems.TwistedNecklaces
